// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#include "../ui.h"
#include <stdio.h>

#define COLOR_WHITE_GRAY        0xEAEAEB
#define COLOR_WHITE             0xE5E4E4
#define COLOR_BLUE              0x007BFF
#define COLOR_RED               0xFF0000
#define COLOR_GREEN             0x00FF00
#define COLOR_ORANGE            0xFFA500 
#define COLOR_BLACK             0x000000
#define COLOR_GRAY              0x464646
#define INDICATOR_TEMP          COLOR_BLUE
#define INDICATOR_SET           COLOR_WHITE_GRAY
#define INDICATOR_BACKGROUND    COLOR_GRAY
#define LABEL_TEMP_COLOR        COLOR_BLUE
#define LABEL_SET_COLOR         COLOR_WHITE

void ui_ScreenPlay_screen_init(void)
{
    // Create main screen
    ui_ScreenPlay = lv_obj_create(NULL);
    if (ui_ScreenPlay == NULL) return;
    
    lv_obj_clear_flag(ui_ScreenPlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_ScreenPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Set Temp ARC
    ui_ArcSetTemp = lv_arc_create(ui_ScreenPlay);
    lv_obj_set_width(ui_ArcSetTemp, 465);
    lv_obj_set_height(ui_ArcSetTemp, 465);
    lv_obj_set_align(ui_ArcSetTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ArcSetTemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ArcSetTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_range(ui_ArcSetTemp, MIN_TEMP, MAX_TEMP);  // Temperature range 0-100°C
    lv_arc_set_value(ui_ArcSetTemp, DEFAULT_TEMP);
    lv_obj_set_style_arc_color(ui_ArcSetTemp, lv_color_hex(INDICATOR_BACKGROUND), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSetTemp, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSetTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_set_style_arc_color(ui_ArcSetTemp, lv_color_hex(INDICATOR_SET), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSetTemp, 120, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSetTemp, 22, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_ArcSetTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Temp ARC
    ui_ArcTemp = lv_arc_create(ui_ScreenPlay);
    lv_obj_set_width(ui_ArcTemp, 465);
    lv_obj_set_height(ui_ArcTemp, 465);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ArcTemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ArcTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_arc_set_range(ui_ArcTemp, MIN_TEMP, MAX_TEMP);  // Temperature range 0-100°C
    lv_arc_set_value(ui_ArcTemp, DEFAULT_TEMP);
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(INDICATOR_BACKGROUND), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(INDICATOR_TEMP), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 120, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 22, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    
    lv_obj_set_style_opa(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelTemp, 400);
    lv_obj_set_height(ui_LabelTemp, 50);
    lv_obj_set_x(ui_LabelTemp, 0);
    lv_obj_set_y(ui_LabelTemp, 40);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelTemp, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LabelTemp, "Temp: 25°C");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(LABEL_TEMP_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSetTemp = lv_label_create(ui_ScreenPlay);
    lv_obj_set_width(ui_LabelSetTemp, 400);
    lv_obj_set_height(ui_LabelSetTemp, 50);
    lv_obj_set_x(ui_LabelSetTemp, 0);
    lv_obj_set_y(ui_LabelSetTemp, -40);
    lv_obj_set_align(ui_LabelSetTemp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelSetTemp, LV_LABEL_LONG_DOT);
    char buff[12];
    sprintf(buff, "Set: %d°C", DEFAULT_TEMP);
    lv_label_set_text(ui_LabelSetTemp, buff);
    lv_obj_set_style_text_color(ui_LabelSetTemp, lv_color_hex(LABEL_SET_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    /*
    //BUTTON
    ui_ButtonScrPlay1 = lv_btn_create(ui_ScreenPlay);
    lv_obj_set_width(ui_ButtonScrPlay1, 100);
    lv_obj_set_height(ui_ButtonScrPlay1, 50);
    lv_obj_set_x(ui_ButtonScrPlay1, -167);
    lv_obj_set_y(ui_ButtonScrPlay1, -3);
    lv_obj_set_align(ui_ButtonScrPlay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScrPlay1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScrPlay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    */
}
