// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.3
// Project name: rot_lms

#ifndef _ROT_LMS_UI_H
#define _ROT_LMS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

#define MAX_TEMP 70
#define MIN_TEMP 10
#define DEFAULT_TEMP 25

extern lv_obj_t * ui_ScreenPlay;
extern lv_obj_t * ui_ArcSetTemp;
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelSetTemp;
extern lv_obj_t * ui_ButtonScrPlay1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_clear_png);    // assets\Clear.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets\clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets\clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets\clockwise_hour.png

LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_monos100);
LV_FONT_DECLARE(ui_font_montse100);
LV_FONT_DECLARE(ui_font_montse120);
LV_FONT_DECLARE(ui_font_oneslot100);
LV_FONT_DECLARE(ui_font_oneslot120);
LV_FONT_DECLARE(ui_font_opensansreg22);

void ui_ScreenPlay_screen_init(void);
void ui_event_ButtonScrPlay1(lv_event_t * e);
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
